[package]
name = "ld45"
version = "0.0.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"

[dependencies]
amethyst   = { version = "0.13.2", features = ["vulkan"] }
deathframe = { path = "../deathframe" }
serde      = "1.0.101"
ron        = "0.5.1"
json       = "0.12.0"
bitflags   = "=1.0.4"  # https://github.com/rust-lang/rust/issues/59134#issuecomment-489430178

[features]
nightly = ["amethyst/nightly"]
