[package]
name = "ld45"
version = "0.0.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"

[dependencies]
amethyst   = { version = "0.13.1", features = ["vulkan"] }
deathframe = { path = "../deathframe" }
serde      = "1.0.101"

[features]
nightly = ["amethyst/nightly"]
